default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: hive

test:
  <<: *default
  database: hive_test

production:
  <<: *default
  database: hive_production
